spring:
  application:
    name: spring-micro-nexus
    datasource:
      url: jdbc:postgresql://localhost:5432/${DB_NAME:spring_nexus}
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:password}
      driver-class-name: org.postgresql.Driver

      autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  logging:
    level:
      sql: DEBUG